# Generated by Django 5.2.5 on 2025-08-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('cc', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('height', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
