# Generated by Django 5.2.5 on 2025-08-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_firstname_person_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('cc', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('height', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('imc', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
