# Generated by Django 5.2.5 on 2025-08-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_people_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='imc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
