# Generated by Django 5.2.5 on 2025-08-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_people_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='state',
            field=models.CharField(default=' '),
        ),
    ]
